set(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${REPOSITORY_ROOT}/src/main.cpp" MAIN_TEXT)
file(READ "${REPOSITORY_ROOT}/mod.json" MOD_JSON)

if(NOT MAIN_TEXT MATCHES "#include[ \t]*<cvolton\\.level-id-api/include/EditorIDs\\.hpp>")
    message(FATAL_ERROR "editor level ID bridge must include the public Editor Level ID API")
endif()
if(NOT MOD_JSON MATCHES "cvolton\\.level-id-api")
    message(FATAL_ERROR "mod.json must declare the Editor Level ID API dependency")
endif()
if(NOT MOD_JSON MATCHES "cvolton\\.level-id-api[\" ]*:[\" ]*>=2\\.0\\.0")
    message(FATAL_ERROR "Editor Level ID API dependency must require >=2.0.0")
endif()
if(NOT MAIN_TEXT MATCHES "GJLevelType::Editor")
    message(FATAL_ERROR "level-start bridge must distinguish editor levels")
endif()
if(NOT MAIN_TEXT MATCHES "EditorIDs::getID[ \t\n]*\\([ \t\n]*level[ \t\n]*\\)")
    message(FATAL_ERROR "editor level-start bridge must use EditorIDs::getID(level)")
endif()
if(NOT MAIN_TEXT MATCHES "m_levelID\\.value")
    message(FATAL_ERROR "non-editor level-start bridge must use m_levelID.value()")
endif()
if(NOT MAIN_TEXT MATCHES "raw_level_id")
    message(FATAL_ERROR "level-start bridge must retain a validated raw level ID")
endif()
if(NOT MAIN_TEXT MATCHES "<=[ \t\n]*0")
    message(FATAL_ERROR "level-start bridge must reject non-positive IDs")
endif()
if(NOT MAIN_TEXT MATCHES "-editor")
    message(FATAL_ERROR "editor level keys must use the -editor suffix")
endif()

message(STATUS "MoniDash Geode editor level ID contract passed")
