set(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${REPOSITORY_ROOT}/src/main.cpp" MAIN_TEXT)

if(NOT MAIN_TEXT MATCHES "\\$on_mod\\(Loaded\\)")
    message(FATAL_ERROR "Geode bootstrap must use the Loaded hook")
endif()
if(NOT MAIN_TEXT MATCHES "getSaveDir")
    message(FATAL_ERROR "Geode bootstrap must use Mod::get()->getSaveDir()")
endif()
if(NOT MAIN_TEXT MATCHES "telemetry" OR NOT MAIN_TEXT MATCHES "sessions")
    message(FATAL_ERROR "Geode bootstrap must use the telemetry/sessions root")
endif()
if(NOT MAIN_TEXT MATCHES "SessionStore::recover")
    message(FATAL_ERROR "Geode bootstrap must call SessionStore::recover")
endif()

message(STATUS "MoniDash Geode bootstrap contract passed")
