set(MAIN_TEXT "")
file(READ "${CMAKE_CURRENT_LIST_DIR}/../src/main.cpp" MAIN_TEXT)

if(NOT MAIN_TEXT MATCHES "#include[ \t]*<Geode/modify/PlayerObject\\.hpp>")
    message(FATAL_ERROR "death bridge must include the PlayerObject modify header")
endif()
if(NOT MAIN_TEXT MATCHES "class[ \t\n]+\\$modify\\(PlayerObject\\)[ \t\n]*\\{")
    message(FATAL_ERROR "death bridge must use the class PlayerObject modification declaration")
endif()
if(NOT MAIN_TEXT MATCHES "void[ \t\n]+playerDestroyed[ \t\n]*\\([ \t\n]*bool[ \t]+noEffects[ \t\n]*\\)")
    message(FATAL_ERROR "death bridge must use the exact playerDestroyed signature")
endif()

string(REGEX MATCHALL "PlayerObject::playerDestroyed[ \t\n]*\\([ \t\n]*noEffects[ \t\n]*\\)" ORIGINAL_CALLS "${MAIN_TEXT}")
list(LENGTH ORIGINAL_CALLS ORIGINAL_CALL_COUNT)
if(NOT ORIGINAL_CALL_COUNT EQUAL 1)
    message(FATAL_ERROR "death bridge must call the original playerDestroyed exactly once")
endif()

string(FIND "${MAIN_TEXT}" "void playerDestroyed" PLAYER_DESTROYED_START)
string(SUBSTRING "${MAIN_TEXT}" ${PLAYER_DESTROYED_START} -1 PLAYER_DESTROYED_TEXT)
string(FIND "${PLAYER_DESTROYED_TEXT}" "};" PLAYER_CLASS_END)
string(SUBSTRING "${PLAYER_DESTROYED_TEXT}" 0 ${PLAYER_CLASS_END} PLAYER_DESTROYED_TEXT)
string(FIND "${PLAYER_DESTROYED_TEXT}" "PlayerObject::playerDestroyed(noEffects);" ORIGINAL_CALL_POSITION)
string(FIND "${PLAYER_DESTROYED_TEXT}" "if (!core || !active_level_id)" GUARD_POSITION)
string(FIND "${PLAYER_DESTROYED_TEXT}" "core->record_death(monidash::Death{*active_level_id});" RECORD_POSITION)
if(ORIGINAL_CALL_POSITION LESS 0 OR GUARD_POSITION LESS 0 OR RECORD_POSITION LESS 0 OR RECORD_POSITION LESS ORIGINAL_CALL_POSITION)
    message(FATAL_ERROR "death must be recorded after the original call with core and active-level guards")
endif()

if(NOT MAIN_TEXT MATCHES "record_death")
    message(FATAL_ERROR "death bridge must record deaths through core")
endif()
if(PLAYER_DESTROYED_TEXT MATCHES "PlayLayer::destroyPlayer|m_isDead|playDeathEffect|[Dd]eath[ \t_-]*[Tt]racker|DeathTracker|death_tracker|resetLevel|raw_x|percentage|recent_input|input")
    message(FATAL_ERROR "death bridge contains a forbidden death hook, state, telemetry, or integration token")
endif()
if(PLAYER_DESTROYED_TEXT MATCHES "sleep|debounce|rate|threshold|milliseconds|chrono|offset|timing")
    message(FATAL_ERROR "death bridge must not use timing, debounce, rate-limit, or offset logic")
endif()
if(PLAYER_DESTROYED_TEXT MATCHES "(player|this)[ \t\n]*->[ \t\n]*[A-Za-z_]")
    message(FATAL_ERROR "death bridge must not read PlayerObject members")
endif()

message(STATUS "MoniDash Geode death contract passed")
