set(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${REPOSITORY_ROOT}/src/main.cpp" MAIN_TEXT)

if(NOT MAIN_TEXT MATCHES "\\$modify\\(PlayLayer\\)")
    message(FATAL_ERROR "level-start bridge must modify PlayLayer")
endif()
if(NOT MAIN_TEXT MATCHES "#include[ \t]*<Geode/modify/PlayLayer\\.hpp>")
    message(FATAL_ERROR "level-start bridge must include the PlayLayer modify header")
endif()
if(NOT MAIN_TEXT MATCHES "bool[ \t\n]+init[ \t\n]*\\([ \t\n]*GJGameLevel[ \t]*\\*[ \t]*level[ \t]*,[ \t\n]*bool[ \t]+useReplay[ \t]*,[ \t\n]*bool[ \t]+dontCreateObjects[ \t]*\\)")
    message(FATAL_ERROR "level-start bridge must use the exact three-parameter PlayLayer init signature")
endif()
if(NOT MAIN_TEXT MATCHES "PlayLayer::init[ \t\n]*\\([ \t\n]*level[ \t]*,[ \t\n]*useReplay[ \t]*,[ \t\n]*dontCreateObjects[ \t\n]*\\)")
    message(FATAL_ERROR "level-start bridge must call the original init")
endif()
if(NOT MAIN_TEXT MATCHES "record_level_started")
    message(FATAL_ERROR "level-start bridge must call the core level-start method")
endif()
if(MAIN_TEXT MATCHES "[Dd]eath[ \t_-]*[Tt]racker|DeathTracker|death_tracker")
    message(FATAL_ERROR "level-start bridge must not reference Death Tracker")
endif()

message(STATUS "MoniDash Geode level-start contract passed")
