set(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")

file(READ "${REPOSITORY_ROOT}/mod.json" MOD_JSON)

string(JSON MOD_ID GET "${MOD_JSON}" id)
string(JSON MOD_NAME GET "${MOD_JSON}" name)
string(JSON MOD_VERSION GET "${MOD_JSON}" version)
string(JSON MOD_DEVELOPER GET "${MOD_JSON}" developer)
string(JSON MOD_DESCRIPTION GET "${MOD_JSON}" description)
string(JSON MOD_GEODE GET "${MOD_JSON}" geode)
string(JSON MOD_GD_WIN GET "${MOD_JSON}" gd win)

if(NOT MOD_ID STREQUAL "migas.monidash")
    message(FATAL_ERROR "unexpected mod id: ${MOD_ID}")
endif()
if(NOT MOD_NAME STREQUAL "MoniDash")
    message(FATAL_ERROR "unexpected mod name: ${MOD_NAME}")
endif()
if(NOT MOD_VERSION STREQUAL "v0.1.0")
    message(FATAL_ERROR "unexpected mod version: ${MOD_VERSION}")
endif()
if(NOT MOD_DEVELOPER STREQUAL "migas")
    message(FATAL_ERROR "unexpected mod developer: ${MOD_DEVELOPER}")
endif()
if(NOT MOD_DESCRIPTION MATCHES "early local-first telemetry foundation")
    message(FATAL_ERROR "description does not identify the early local-first foundation")
endif()
if(NOT MOD_DESCRIPTION MATCHES "does not yet capture gameplay")
    message(FATAL_ERROR "description does not state that gameplay is not captured")
endif()
if(NOT MOD_DESCRIPTION MATCHES "read Death Tracker")
    message(FATAL_ERROR "description does not state that Death Tracker is not read")
endif()
if(NOT MOD_GEODE STREQUAL "5.8.2")
    message(FATAL_ERROR "unexpected Geode target: ${MOD_GEODE}")
endif()
if(NOT MOD_GD_WIN STREQUAL "2.2081")
    message(FATAL_ERROR "unexpected Geometry Dash target: ${MOD_GD_WIN}")
endif()

file(READ "${REPOSITORY_ROOT}/CMakeLists.txt" CMAKE_TEXT)
if(NOT CMAKE_TEXT MATCHES "option\\(MONIDASH_BUILD_GEODE_MOD[ \\t]+.*OFF")
    message(FATAL_ERROR "Geode packaging option is not explicit and OFF by default")
endif()
if(NOT CMAKE_TEXT MATCHES "MONIDASH_GEODE_SDK")
    message(FATAL_ERROR "Geode SDK cache path is missing")
endif()
if(NOT CMAKE_TEXT MATCHES "GEODE_CLI")
    message(FATAL_ERROR "Geode CLI cache path is missing")
endif()
if(NOT CMAKE_TEXT MATCHES "setup_geode_mod")
    message(FATAL_ERROR "setup_geode_mod is not wired")
endif()
if(NOT CMAKE_TEXT MATCHES "target_link_libraries\\(monidash_geode_mod[ \\t]+monidash_core\\)")
    message(FATAL_ERROR "Geode target must use the plain link signature compatible with setup_geode_mod")
endif()
if(NOT CMAKE_TEXT MATCHES "cxx_std_23")
    message(FATAL_ERROR "Geode target does not request C++23")
endif()

message(STATUS "MoniDash packaging contract passed")
